apiRules:
- include:
    uidRegex: ^OmiyaGames\.Template$
    type: Namespace
- include:
    uidRegex: ^OmiyaGames\.Template\.Editor$
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace